version: '2.1'

services:

  # Run service locally from current directory
  app:
    image: ${DC_IMAGE}
    command:
      /usr/bin/apisite --db.schema rpc --http_addr :8080
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${APP_SITE}"
      - "traefik.frontend.rule=Host:${APP_SITE}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - .:/opt/apisite
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGSSLMODE=${PGSSLMODE}
      - PGAPPNAME=${PGAPPNAME}

  # Used for docker image with all sources
  dist:
    image: ${PRG}:${VERSION}
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGSSLMODE=${PGSSLMODE}
    networks:
      - web
    build:
      context: .

networks:
  web:
    external:
      name: ${DCAPE_NET}
